export const CAPABILITIES_BY_VERTICAL: Record<string, string[]> = {
  retail: ['Order Management','Returns & Refunds','Product Search','Inventory Lookup',
           'Store Locator','Shipment Tracking','Add to Cart / Reorder','Cancel Order',
           'Loyalty & Rewards','FAQ / Knowledge Base','Missing Items / Collectibles','Escalation to Human'],
  bfsi: ['Account Balance & Statements','Transaction History','Loan Applications',
         'Credit Card Support','Fraud Reporting','Fund Transfers','Investment Queries',
         'Branch / ATM Locator','KYC & Onboarding','FAQ / Knowledge Base','Escalation to Human'],
  healthcare: ['Appointment Booking','Patient Registration','Symptom Checker',
               'Prescription Refills','Insurance Verification','Lab Results Inquiry',
               'Billing & Payment Support','Doctor / Specialist Lookup',
               'Emergency Triage Guidance','FAQ / Knowledge Base','Escalation to Human'],
  telecom: ['Bill Payment & Queries','Data Plan Management','Technical Support',
            'SIM Activation & Porting','Roaming & International Charges',
            'Network Outage Status','Device Troubleshooting','Upgrade & Plan Change',
            'FAQ / Knowledge Base','Escalation to Human'],
  hospitality: ['Room Booking & Reservations','Check-in / Check-out','Concierge Services',
                'Restaurant Reservations','Spa & Amenities Booking','Loyalty Points & Rewards',
                'Local Attractions & Transport','Housekeeping Requests',
                'FAQ / Knowledge Base','Escalation to Human'],
  ecommerce: ['Product Search & Discovery','Order Tracking','Returns & Refunds',
              'Payment Support','Wishlist & Saved Items','Personalised Recommendations',
              'Seller / Merchant Support','Coupon & Promotions',
              'FAQ / Knowledge Base','Escalation to Human'],
  utilities: ['Bill Payment & Queries','Usage Reports','Outage Reporting',
              'Service Connection / Disconnection','Meter Reading Submission',
              'Energy Efficiency Advisory','Field Technician Scheduling',
              'FAQ / Knowledge Base','Escalation to Human'],
  generic: [],
}
